webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
plugins:
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  softwareupdate:
    checks:
      octoprint:
        update_folder: /home/pi/BEEweb
    octoprint_restart_command: sudo service beeweb restart
    environment_restart_command: sudo shutdown -r now
system:
  actions:
  - name: Shutdown
    command: sudo shutdown -h now
    action: shutdown
    confirm: You are about to shutdown the system.
    async: true
    ignore: true
  - name: Reboot
    command: sudo shutdown -r now
    action: reboot
    confirm: You are about to reboot the system
    async: true
    ignore: true
  - name: Restart BEEsoft
    command: sudo service beeweb restart
    action: restart
    confirm: You are about to restart BEEsoft.web
    async: true
    ignore: true
slicing:
  defaultProfiles:
    cura: a117_-_chocolate_brown_med_beethefirst
